apiVersion: apps/v1
kind: Deployment
metadata:
  name: conciliacion
  labels:
    app: conciliacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conciliacion
  template:
    metadata:
      labels:
        app: conciliacion
    spec:
      containers:
        - name: conciliacion
          image: 634178970039.dkr.ecr.us-east-1.amazonaws.com/grupo1:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080